### ISSUE TITLE
Brightness slider broken?

### ISSUE THREAD

**Issue by jgx0** [HikariKnight/material-awesome#10]
when I use the brightness slider all the way up, it just goes back down to half, but i can move it down as much as I want. Please help me fix this!!
Thank you

**Comment by HikariKnight** [comment]
It is a bug in how the slider and the dirty calculation works for it, the brightness slider (the way i implemented it to work on my laptop) is essentially just a hack since my laptop has no proper back-light controls exposed :(
unfortunately for some reason i cant tell it to stop at 99% as the bug happens when it reaches 100% (on my end)

i am however working on a major overhaul of the project so i will be testing some newer solutions to brightness

**Comment by jgx0** [comment]
@HikariKnight thanks for saying!

**Comment by HikariKnight** [comment]
@orangemn6 hey, this should be fixed now and if you want to backport the "fix" to material-awesome for awesome 4.3-stable then you can make the brightness slider call this script instead of xrandr directly.

Here is the script i use for the master branch
https://github.com/HikariKnight/material-awesome/blob/master/utilities/laptop-brightness

you will have to edit this file for awesome4.3-stable
https://github.com/HikariKnight/material-awesome/blob/awesome4.3-stable/widget/brightness/brightness-slider.lua

**Comment by jgx0** [comment]
@HikariKnight thanks for helping! I am trying right now, and it seems to work.
