### ISSUE TITLE
app list has weird text backround

### ISSUE THREAD

**Issue by mrhappy200** [HikariKnight/material-awesome#18]
So I absolutely love this awesomewm theme it really great but I am having this weird issue with the app launcher, see the image.
this is my awesome version (git) awesome v4.3-1159-geddabebac (Too long)

![ksnip_20211001-081538](https://user-images.githubusercontent.com/74416511/135575299-500f42fc-4e2d-4d1e-b1cf-1680500480b2.png)

**Comment by HikariKnight** [comment]
hey @mrhappy200 
do you have compton or picom installed?
it could also be an issue with the rofi theme itself

it is not related to awesome since the launcher is entierly rofi which uses its own theme

**Comment by mrhappy200** [comment]
I have the reccomended version of picom installed

**Comment by HikariKnight** [comment]
@mrhappy200 have you done any changes to the [rofi.rasi](https://github.com/HikariKnight/material-awesome/tree/master/configuration/rofi/appmenu/rofi.rasi) theme file?

Not really sure what else could be causing it other than a misconfigured theme file for rofi 🤔
another thing to try is to run `rofi -show drun -theme $HOME/.config/awesome/configuration/rofi/appmenu/rofi.rasi -run-command "/bin/bash -c -i \'shopt -s expand_aliases; {cmd}\'"` and see if it complains anything about the theme in the terminal.
this is the same command run when you do open the app menu or hit the hotkey for rofi

PS: also what distro are you using and what desktop environment did you come from? (im guessing kde plasma since i see dolphin) so that i can try recreate the issue in a VM

**Comment by IceDBorn** [comment]
I have the same issue and I'm using the latest master build

**Comment by HikariKnight** [comment]
hi @IceDBorn i have not been able to replicate the issue so it would be nice to get some info so i can investigate inside a VM

Distro:
Original Desktop Environment (if you have multiple installed then list them all, window managers excluded):
Have you done any changes to /etc/environment or ~/.Xresources? if so what:

use this for code or text file blocks for readability
\`\`\`
text
\`\`\`

**Comment by IceDBorn** [comment]
@HikariKnight 
Distro: ```Arch Linux```
Desktop Enviroment: ```KDE Plasma```
I have not made any changes to /etc/environment or ~/.Xresources.
I'm going to clean install Arch soon, so I'll be able to tell if having plasma installed breaks rofi.

**Comment by HikariKnight** [comment]
@IceDBorn thanks i will attempt to recreate it tomorrow or next weekend, depends how my week will be.

I know i had some weirdness with plasmashell in the background doing some kde stuff when i logged into awesome from sddm in the past, not sure if it is no longer the case. but we will see when i do my testing.

**Comment by IceDBorn** [comment]
@HikariKnight I did a clean install of arch linux, sddm + awesome and rofi has the same issue.

**Comment by HikariKnight** [comment]
@mrhappy200 @IceDBorn 

seems to be an issue only on arch based distros, so could be a rofi version problem where rofi has introduced new themeing options meaning that the rofi.rasi theme file has to be fixed for rofi 1.7

i am still using rofi 1.5.4 :thinking: 
at least that is my theory as i tried going from gnome, xfce, kde plasma, etc to material-awesome and they all produced the same issue so it most likely is an issue with the theme file being incompatible with the newer version since rofi-theme-selector does not have the same issue when using built in themes.

**Comment by HikariKnight** [comment]
This has been fixed in the latest commit to both lua5.4 branch and master branch :)
