### ISSUE TITLE
Reduce width of both the bars and reduce icon sizes 

### ISSUE THREAD

**Issue by dhaval9911** [HikariKnight/material-awesome#7]
I am using this configuration but maybe this is more comfortable with big monitor and i m using in a laptop ..i m kindaa want to reduce width of both panels and size of icons  pls help

**Comment by linuxdotexe** [comment]
You can do that by navigating to `awesome/layout` and find the `top-panel.lua` file there and left-panel configs in the left-panel folder under `init.lua`.  Change the height or width to a value suitable for you.  Default will be `dpi(45)`. Do not go under 40 for the left panel since that will make the icons look a bit weird.
